# Generated by Django 2.0.6 on 2018-06-10 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 10, 6, 55, 27, 931942, tzinfo=utc)),
        ),
    ]
